services:
  pihole:
    image: pihole/pihole:latest
    networks:
      - traefik
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      # - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      # - "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'Europe/Berlin'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: ''
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - pihole:/etc/pihole
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 30s
        order: start-first
        monitor: 20s
      labels:
        - "traefik.enable=true"
        - "traefik.stack.network=traefik"  

        - "traefik.http.routers.pihole.rule=Host(`pihole.hartig.es`)"
        - "traefik.http.routers.pihole.entrypoints=https"
        - "traefik.http.routers.pihole.tls=true"

        - "traefik.http.services.pihole.loadbalancer.server.port=80"

        
        - "traefik.constraint=proxy-public"
        
        - "traefik.http.routers.pihole.middlewares=authentik@swarm"

volumes:
  pihole:
    driver: local

networks:
  traefik:
    external: trueit